services:
  web:
    env_file:
      - .env
    build: .
    command: sh -c 'cd sportinj &&
                python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - .data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/redis

volumes:
  redis_volume:
