services:
  web:
    env_file:
      - .env
    build: .
    command: sh -c 'python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: sportinj-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
