services:
  web:
    env_file:
      - .env
    restart: unless-stopped
    image: ghcr.io/alekseybeloded/football_injuries:${VERSION}
    container_name: web
    command: sh -c 'python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn sportinj.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - static_volume:/app/sportinj/staticfiles
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx
    volumes:
      - static_volume:/app/sportinj/staticfiles
      - media_volume:/app/sportinj/media
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/redis

  celery:
    env_file:
      - .env
    restart: unless-stopped
    container_name: celery
    build: ghcr.io/alekseybeloded/football_injuries:${VERSION}
    command: sh -c 'cd sportinj &&
                celery -A sportinj worker --beat --scheduler django --loglevel=info'

volumes:
  static_volume:
  redis_volume:
