services:
  web:
    env_file:
      - .env
    restart: unless-stopped
    image: ghcr.io/alekseybeloded/football_injuries:${VERSION}
    command: sh -c 'python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn sportinj.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - static_volume:/app/sportinj/staticfiles
      - media_volume:/app/sportinj/media
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: sportinj-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - static_volume:/app/sportinj/staticfiles
      - media_volume:/app/sportinj/media
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
