services:
  web:
    env_file:
      - .env
    restart: unless-stopped
    image: ghcr.io/alekseybeloded/football_injuries:${VERSION}
    command: sh -c 'python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn sportinj.wsgi:application --bind 0.0.0.0'
    volumes:
      - static_volume:/app/sportinj/staticfiles
      - media_volume:/app/sportinj/media
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: sportinj-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .data/postgres:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - static_volume:/app/sportinj/staticfiles
      - media_volume:/app/sportinj/media
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    ports:
      - 8000:8000
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
