# Generated by Django 4.2.11 on 2024-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_injury_slug_player_slug_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injury',
            name='slug',
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
