# Generated by Django 4.2.11 on 2024-05-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_injury_slug_alter_player_slug_alter_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injury',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='injuries',
            field=models.ManyToManyField(blank=True, related_name='injuries', to='resources.injury'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='resources.team'),
        ),
    ]
