# Generated by Django 4.2.11 on 2024-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_injury_player_player_injuries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injury',
            options={'ordering': ['time_create'], 'verbose_name_plural': 'Injuries   '},
        ),
        migrations.AlterField(
            model_name='injury',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='injuries',
            field=models.ManyToManyField(blank=True, related_name='players', to='resources.injury'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
