# Generated by Django 4.2.11 on 2024-05-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_injury_options_alter_injury_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='time_uodate',
            new_name='time_update',
        ),
    ]
