# Generated by Django 4.2.11 on 2024-08-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_rename_time_uodate_player_time_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injury',
            options={'ordering': ['time_create'], 'verbose_name_plural': 'Injuries'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='injuries',
        ),
        migrations.AddField(
            model_name='injury',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='resources.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='resources.team'),
        ),
    ]
