name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install dependencies
        run: pip install --upgrade pip && pip install poetry && poetry install
      - name: run ruff
        uses: chartboost/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: sportinj
          POSTGRES_USER: sportinj
          POSTGRES_PASSWORD: sportinj
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U sportinj"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install dependencies
        run: pip install --upgrade pip && pip install poetry && poetry install
      - name: Run migrations
        run: poetry run python manage.py migrate

      - name: run pytest
        run: poetry run pytest --cov -vv .
